package com.romens.yjk.health.db.dao;

import android.database.sqlite.SQLiteDatabase;

import com.romens.yjk.health.db.entity.DiscoveryEntity;
import com.romens.yjk.health.db.entity.DrugGroupEntity;
import com.romens.yjk.health.db.entity.EatDrugUserEntity;
import com.romens.yjk.health.db.entity.LocationAddressEntity;
import com.romens.yjk.health.db.entity.RemindEntity;
import com.romens.yjk.health.db.entity.SearchHistoryEntity;
import com.romens.yjk.health.model.ShopCarEntity;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig discoveryDaoConfig;
    private final DaoConfig drugGroupDaoConfig;

    private final DiscoveryDao discoveryDao;
    private final DrugGroupDao drugGroupDao;

    private final DaoConfig locationAddressDaoConfig;
    private final LocationAddressDao locationAddressDao;

    private final RemindDao remindDao;
    private final DaoConfig remindDaoConfig;

    private final SearchHistoryDao searchHistoryDao;
    private final  DaoConfig searchResultDaoConfig;

    private final  EatDrugUserDao eatDrugUserDao;
    private final DaoConfig eatDrugUserDaoConfig;

    private final ShopCarDao shopCarDao;
    private final DaoConfig shopCarDaoConfig;


    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        discoveryDaoConfig = daoConfigMap.get(DiscoveryDao.class).clone();
        discoveryDaoConfig.initIdentityScope(type);
        discoveryDao = new DiscoveryDao(discoveryDaoConfig, this);
        registerDao(DiscoveryEntity.class, discoveryDao);

        drugGroupDaoConfig = daoConfigMap.get(DrugGroupDao.class).clone();
        drugGroupDaoConfig.initIdentityScope(type);
        drugGroupDao = new DrugGroupDao(drugGroupDaoConfig, this);
        registerDao(DrugGroupEntity.class, drugGroupDao);

        locationAddressDaoConfig = daoConfigMap.get(LocationAddressDao.class).clone();
        locationAddressDaoConfig.initIdentityScope(type);
        locationAddressDao = new LocationAddressDao(locationAddressDaoConfig, this);
        registerDao(LocationAddressEntity.class, locationAddressDao);

        remindDaoConfig = daoConfigMap.get(RemindDao.class).clone();
        remindDao=new RemindDao(remindDaoConfig,this);
        registerDao(RemindEntity.class,remindDao);

        searchResultDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDao =new SearchHistoryDao(searchResultDaoConfig,this);
        registerDao(SearchHistoryEntity.class, searchHistoryDao);

        eatDrugUserDaoConfig = daoConfigMap.get(EatDrugUserDao.class).clone();
        eatDrugUserDao = new EatDrugUserDao(eatDrugUserDaoConfig, this);
        registerDao(EatDrugUserEntity.class,eatDrugUserDao);

        shopCarDaoConfig = daoConfigMap.get(ShopCarDao.class).clone();
        shopCarDaoConfig.initIdentityScope(type);
        shopCarDao = new ShopCarDao(shopCarDaoConfig, this);
        registerDao(ShopCarEntity.class, shopCarDao);
    }

    public void clear() {
        discoveryDaoConfig.getIdentityScope().clear();
        drugGroupDaoConfig.getIdentityScope().clear();
        locationAddressDaoConfig.getIdentityScope().clear();
        remindDaoConfig.getIdentityScope().clear();
        searchResultDaoConfig.getIdentityScope().clear();
        eatDrugUserDaoConfig.getIdentityScope().clear();
        shopCarDaoConfig.getIdentityScope().clear();
    }

    public DiscoveryDao getDiscoveryDao() {
        return discoveryDao;
    }

    public DrugGroupDao getDrugGroupDao() {
        return drugGroupDao;
    }

    public LocationAddressDao getLocationAddressDao() {
        return locationAddressDao;
    }

    public RemindDao getRemindDao() {
        return remindDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public EatDrugUserDao getEatDrugUserDao() {
        return eatDrugUserDao;
    }
    public ShopCarDao getShopCarDao(){
        return  shopCarDao;
    }
}
